version: '3'

volumes:
  postgres_volume:

services:
  pg-local:
    image: postgres:14-alpine3.17
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_db
      POSTGRES_PASSWORD: test_db
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data